### ISSUE TITLE
Maybe mention lighgallery licence on stimulus components page?

### ISSUE THREAD

**Issue by kentarofujiy** [stimulus-components/stimulus-lightbox#7]
I know they deserve being paid for their hard work, but it doesn't hurt to let people know before they add the component to their project.

**Comment by guillaumebriday** [comment]
Hey @kentarofujiy 

You're right, I already mentioned them on the main page of the documentation like any other controllers that use an external library

<img width="616" alt="Screenshot 2022-10-31 at 14 09 04" src="https://user-images.githubusercontent.com/8252238/199015308-6d3ba052-68ad-432d-b351-57fa9153f54a.png">

👍

**Comment by danhayden** [comment]
There is still no mention of the [lightgalleryjs license](https://www.lightgalleryjs.com/license/) on the [Stimulus Lightbox page](https://www.stimulus-components.com/docs/stimulus-lightbox/).

I feel this is misleading as it would appear that Stimulus Lightbox is available to use free in any project (due to the MIT license) however this is not the case because of the lightgalleryjs license as mentioned in https://github.com/stimulus-components/stimulus-lightbox/issues/2

Is there an intention to replace lightgalleryjs with a more open alternative such as https://fslightbox.com? (https://fslightbox.com/licenses)
